ARG IMAGE_TYPE="stable"
ARG IMAGE="altlinux.space/alt-atomic/onyx:stable"

FROM $IMAGE

ARG BUILD_TYPE="default"

ENV IMAGE_TYPE=$IMAGE_TYPE
ENV BUILD_TYPE=$BUILD_TYPE

RUN --mount=type=bind,source=./src,target=/src \
    apt-get update && \
    /src/packages/02-nvidia-packages.sh && \
    /src/configuration/02-nvidia.sh && \
    /src/configuration/03-kernel.sh && \
    /src/packages/99-apt-ending.sh
