name: Build noightly image
description: Build, rechunk, lint and push nightly image

inputs:
  build:
    required: true
    description: ''
  image-name:
    required: true
    description: ''
  name-pretty:
    required: true
    description: ''
  date:
    required: true
    description: ''
  pretty-date:
    required: true
    description: ''
  commit:
    required: true
    description: ''
  registry-token:
    required: true
    description: ''
  cosign-image-sign:
    required: true
    description: ''
  cosign-password:
    required: true
    description: ''
  local-build-name:
    required: true
    description: ''
    default: localhost/onyx
  registry:
    required: true
    description: ''
    default: altlinux.space

runs:
  using: composite
  steps:
  - name: Build sisyphus default image
    run: |
      set -x

      if [[ "${{ inputs.build }}" == "default" ]]; then
        IMAGE="${{ inputs.registry }}/alt-atomic/core/stable:${{ inputs.date }}"
      else
        IMAGE="${{ inputs.registry }}/${{ github.repository }}/prerelease:${{ inputs.commit }}"
      fi

      podman build \
        --tag ${{ inputs.local-build-name }} \
        --platform linux/amd64 \
        --build-arg IMAGE=$IMAGE \
        --build-arg BUILD=${{ inputs.build }} \
        --build-arg IMAGE_TYPE=prerelease \
        --file ./container-files/main \
        .

  - name: Rechunk image
    uses: alt-atomic/actions/rechunk@main
    id: rechunk
    with:
      ref: ${{ inputs.local-build-name }}
      prev-ref: ${{ format('{0}/{1}/prerelease:latest', inputs.registry, inputs.image-name) }}
      labels: |
        org.altlinux.repo.date=${{ inputs.pretty-date }}
        org.opencontainers.image.title=ALT Atomic Onyx Prerelease ${{ inputs.name-pretty }}
        org.opencontainers.image.description=ALT Atomic with GNOME, prerelease build ${{ inputs.name-pretty }}
        org.opencontainers.image.source=https://altlinux.space/alt-atomic/onyx
        org.opencontainers.image.licenses=GPL-3.0-or-later
        org.opencontainers.image.vendor=ALT Atomic Team

  - name: Push and sign images
    uses: alt-atomic/actions/push-and-sign@main
    with:
      registry: ${{ inputs.registry }}
      registry-username: "<token>"
      registry-password: ${{ inputs.registry-token }}
      image-name: ${{ format('{0}/prerelease', inputs.image-name) }}
      image-tag: ${{ inputs.commit }}
      local-build-name: ${{ steps.rechunk.outputs.ref }}
      cosign-image-sign: ${{ inputs.cosign-image-sign }}
      cosign-password: ${{ inputs.cosign-password }}
