name: Build stable images

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date tag of Core in format YYYYMMDD. Can be `latest`'
        required: true
        type: string
        default: 'latest'
      git-tag:
        description: 'Git tag of release. Can be `latest`'
        required: true
        type: string
        default: 'latest'

env:
  LOCAL_BUILD_NAME: localhost/onyx
  REGISTRY: altlinux.space

jobs:
  check-tag-and-date:
    name: Check inputs
    runs-on: alt-sisyphus
    strategy:
      matrix:
        include:
          - build: default
            image-name: ${{ github.repository }}
            name-pretty: ''
          - build: nvidia
            image-name: ${{ github.repository }}-nvidia
            name-pretty: (Nvidia)
    container:
      image: altlinux.space/actions/runner/containers:sisyphus
    steps:
      - name: Get date
        id: date
        uses: alt-atomic/actions/parse-date@main
        with:
          date: ${{ github.event.inputs.date }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: target_tag
        uses: alt-atomic/actions/get-tag@main
        with:
          desired-tag: ${{ github.event.inputs.git-tag }}

      - name: Check Docker image existence
        run: |
          if [[ "${{ steps.date.outputs.date }}" != "latest" ]]; then
            if podman pull altlinux.space/alt-atomic/core/stable:${{ steps.date.outputs.date }}; then
              exit 0
            else
              echo "Image does not exist"
              exit 1
            fi
          fi

  build:
    name: Build image
    runs-on: alt-sisyphus
    needs: check-tag-and-date
    strategy:
      matrix:
        build: [default, nvidia]
    container:
      image: altlinux.space/actions/runner/containers:sisyphus
    steps:
      - name: Prepare env
        uses: alt-atomic/actions/prepare-env@main

      - name: Get date
        id: date
        uses: alt-atomic/actions/parse-date@main
        with:
          date: ${{ github.event.inputs.date }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: target_tag
        uses: alt-atomic/actions/get-tag@main
        with:
          desired-tag: ${{ github.event.inputs.git-tag }}

      - name: Checkout target tag
        run: |
          git fetch --all --tags --force
          git checkout ${{ steps.target_tag.outputs.tag }}

      - name: Build sisyphus default image
        run: |
          podman build \
            --tag $LOCAL_BUILD_NAME \
            --platform linux/amd64 \
            --build-arg IMAGE=$REGISTRY/alt-atomic/core/stable:${{ steps.date.outputs.date }} \
            --build-arg BUILD=${{ matrix.build }} \
            --build-arg IMAGE_TYPE=stable \
            --file ./container-files/main \
            .

      - name: Rechunk image
        uses: alt-atomic/actions/rechunk@v1.1
        id: rechunk
        with:
          ref: ${{ env.LOCAL_BUILD_NAME }}
          prev-ref: ${{ format('{0}/{1}/stable:latest', env.REGISTRY, matrix.image-name) }}
          labels: |
            org.altlinux.repo.date=${{ steps.date.outputs.pretty-date }}
            org.opencontainers.image.title=ALT Atomic Onyx ${{ matrix.name-pretty }}
            org.opencontainers.image.description=ALT Atomic with GNOME ${{ matrix.name-pretty }}
            org.opencontainers.image.source=https://altlinux.space/alt-atomic/onyx
            org.opencontainers.image.licenses=GPL-3.0-or-later
            org.opencontainers.image.vendor=ALT Linux Team

      - name: Lint image
        uses: alt-atomic/actions/bootc-lint@main
        with:
          ref: ${{ steps.rechunk.outputs.ref }}

      - name: Push and sign images
        uses: alt-atomic/actions/push-and-sign@main
        with:
          registry: ${{ env.REGISTRY }}
          registry-username: "<token>"
          registry-password: ${{ secrets.REGISTRY_TOKEN }}
          image-name: ${{ format('{0}/stable', matrix.image-name) }}
          image-tag: latest
          image-aliases: ${{ steps.date.outputs.date }} ${{ steps.latest_tag.outputs.tag }}
          local-build-name: ${{ steps.rechunk.outputs.ref }}
          cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
          cosign-password: ${{ secrets.COSIGN_PASSWORD }}
