name: Build nightly images

on:
  workflow_dispatch:
  push:
    branches:
    - 'nightly-*'
    - 'main'
  pull_request:

jobs:
  gather-build-data:
    name: Gather build data
    runs-on: als-tiny

    outputs:
      date: ${{ steps.date.outputs.date }}
      pretty-date: ${{ steps.date.outputs.pretty-date }}
      commit: ${{ steps.get_commit.outputs.commit }} 

    steps:
    - name: Get date
      id: date
      uses: alt-atomic/actions/parse-date@main

    - name: Checkout repository
      uses: actions/checkout@v4

    - id: get_commit
      name: Get current commit
      run: |
        echo "commit=$(git rev-parse HEAD)" >> $FORGEJO_OUTPUT

  build-default:
    name: Build default image
    needs:
    - gather-build-data
    runs-on: als-huge
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ needs.gather-build-data.outputs.commit }}

    - name: Build default image
      uses: ./.forgejo/actions/build-and-push-nightly-image
      with:
        build: default
        image-name: ${{ github.repository }}
        name-pretty: ''
        date: ${{ needs.gather-build-data.outputs.date }}
        pretty-date: ${{ needs.gather-build-data.outputs.pretty-date }}
        commit: ${{ needs.gather-build-data.outputs.commit }}
        registry-token: ${{ secrets.REGISTRY_TOKEN }}
        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}

  build-nvidia:
    name: Build default image
    needs:
    - gather-build-data
    - build-default
    runs-on: als-huge
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ needs.gather-build-data.outputs.commit }}

    - name: Build nvidia image
      uses: ./.forgejo/actions/build-and-push-nightly-image
      with:
        build: nvidia
        image-name: ${{ github.repository }}-nvidia
        name-pretty: (Nvidia)
        date: ${{ needs.gather-build-data.outputs.date }}
        pretty-date: ${{ needs.gather-build-data.outputs.pretty-date }}
        commit: ${{ needs.gather-build-data.outputs.commit }}
        registry-token: ${{ secrets.REGISTRY_TOKEN }}
        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}
