name: Build stable images

on:
  push:
    branches:
    - 'release-*'

env:
  REGISTRY: altlinux.space

  PRETTY_NAME: ALT Atomic Onyx
  VENDOR: ALT Atomic Team
  DESCRIPTION: ALT Atomic with GNOME, stable build
  LICENSES: GPL-3.0-or-later
  URL: alt-atomic.org
  AUTHORS: ALT Atomic Team

jobs:
  gather-build-data:
    name: Gather build data
    runs-on: als-tiny
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus

    outputs:
      core-tag: ${{ steps.core_tag.outputs.core-tag }}
      repo-date: ${{ steps.date.outputs.repo-date }}
      commit: ${{ steps.get_commit.outputs.commit }}
      version: ${{ steps.version.outputs.version }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Read CORE_TAG
      id: core_tag
      run: |
        set -e

        tag=$(cat ./CORE_TAG)
        echo "core-tag=$tag" >> $FORGEJO_OUTPUT

    - name: Calcualte next tag version
      id: version
      run: |
        set -e

        PREFIX=${GITHUB_REF_NAME#release-}
        LAST_TAG=$(git tag -l "${PREFIX}.*" | sort -V | tail -n 1)

        if [ -z "$LAST_TAG" ]; then
            VERSION="${PREFIX}.0"
        else
            VERSION="${LAST_TAG%.*}.$(( ${LAST_TAG##*.} + 1 ))"
        fi

        echo "version=$VERSION" >> $FORGEJO_OUTPUT

    - name: Get core repo date
      id: date
      run: |
        set -e

        date=$(skopeo inspect --format '{{index .Labels "org.altlinux.repo.date"}}' docker://altlinux.space/alt-atomic/core/stable:${{ steps.core_tag.outputs.core-tag }})
        echo "repo-date=$date" >> $FORGEJO_OUTPUT

    - id: get_commit
      name: Get current commit
      run: |
        echo "commit=$(git rev-parse HEAD)" >> $FORGEJO_OUTPUT

  build:
    name: Build ${{ matrix.arch }} images
    needs:
    - gather-build-data
    runs-on: ${{ matrix.runner }}
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus
    strategy:
      matrix:
        arch:
        - amd64
        include:
        - arch: amd64
          larch: x86_64
          runner: als-huge

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ needs.gather-build-data.outputs.commit }}

    - name: Build default image
      id: build-default
      uses: alt-atomic/actions/build-and-push@5ad502a0d068531855a953ccc19481c7e13d8f1a
      with:
        image-name: ${{ format('{0}/rc/{1}', github.repository, matrix.arch) }}
        image-tag: ${{ needs.gather-build-data.outputs.commit }}
        arch: ${{ matrix.arch }}
        containerfile-path: ./container-files/main
        local-build-name: localhost/onyx

        registry-password: ${{ secrets.REGISTRY_TOKEN }}
        rechunk-enabled: true
        experimental-use-chunkah: true
        rechunk-max-layers: 128

        pretty-name: ${{ env.PRETTY_NAME }}
        version: ${{ needs.gather-build-data.outputs.version }}
        vendor: ${{ env.VENDOR }}
        description: ${{ env.DESCRIPTION }}
        licenses: ${{ env.LICENSES }}
        url: ${{ env.URL }}
        authors: ${{ env.AUTHORS }}
        repo-date: ${{ needs.gather-build-data.outputs.repo-date }}

        extra-labels: |
          org.altlinux.installer.has-initial-setup=true

        build-args: |
          ARG_IMAGE=${{ format('{0}/alt-atomic/core/stable:{1}', env.REGISTRY, needs.gather-build-data.outputs.core-tag) }}
          ARG_BUILD=default
          ARG_IMAGE_TYPE=stable
          ARG_VERSION=${{ needs.gather-build-data.outputs.version }}

        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}

    - name: Build nvidia image
      uses: alt-atomic/actions/build-and-push@5ad502a0d068531855a953ccc19481c7e13d8f1a
      with:
        image-name: ${{ format('{0}-nvidia/rc/{1}', github.repository, matrix.arch) }}
        image-tag: ${{ needs.gather-build-data.outputs.commit }}
        arch: ${{ matrix.arch }}
        containerfile-path: ./container-files/main
        local-build-name: localhost/onyx-nvidia

        registry-password: ${{ secrets.REGISTRY_TOKEN }}
        rechunk-enabled: true
        experimental-use-chunkah: true
        rechunk-max-layers: 128

        pretty-name: ${{ env.PRETTY_NAME }} (Nvidia)
        version: ${{ needs.gather-build-data.outputs.version }}
        vendor: ${{ env.VENDOR }}
        description: ${{ env.DESCRIPTION }} (Nvidia)
        licenses: ${{ env.LICENSES }}
        url: ${{ env.URL }}
        authors: ${{ env.AUTHORS }}
        repo-date: ${{ needs.gather-build-data.outputs.repo-date }}

        extra-labels: |
          org.altlinux.installer.has-initial-setup=true

        build-args: |
          ARG_IMAGE=${{ steps.build-default.outputs.ref }}
          ARG_BUILD=nvidia
          ARG_IMAGE_TYPE=stable
          ARG_VERSION=${{ needs.gather-build-data.outputs.version }}

        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}

  manifest:
    name: Multiarch ${{ matrix.name }} manifest push
    needs:
    - build
    - gather-build-data
    runs-on: als-tiny
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus
    strategy:
      matrix:
        include:
        - name: default
          suffix: ''
        - name: nvidia
          suffix: '-nvidia'

    steps:
    - name: Create manifest
      uses: alt-atomic/actions/create-manifest@0a7fd4632a415b0f4316c37d9be29325dbe32af9
      with:
        registry: ${{ env.REGISTRY }}
        registry-username: "<token>"
        registry-password: ${{ secrets.REGISTRY_TOKEN }}
        image-name: ${{ format('{0}{1}/rc', github.repository, matrix.suffix) }}
        arch-tags: amd64
        image-wildcard: ${{ format('{0}/{1}{2}/rc/@ARCH@:{3}', env.REGISTRY, github.repository, matrix.suffix, needs.gather-build-data.outputs.commit) }}
        image-tag: ${{ needs.gather-build-data.outputs.commit }}
        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}
