name: Build nightly images

on:
  workflow_dispatch:
  push:
    branches:
    - 'nightly-*'
    - 'main'
  pull_request:

env:
  REGISTRY: altlinux.space

  PRETTY_NAME: ALT Atomic Onyx Nightly
  VENDOR: ALT Atomic Team
  DESCRIPTION: ALT Atomic with GNOME, nightly build
  LICENSES: GPL-3.0-or-later
  URL: atomic.alt-gnome.ru
  AUTHORS: ALT Atomic Team

jobs:
  gather-build-data:
    name: Gather build data
    runs-on: als-tiny

    outputs:
      date: ${{ steps.date.outputs.date }}
      year: ${{ steps.date.outputs.year }}
      month: ${{ steps.date.outputs.month }}
      day: ${{ steps.date.outputs.day }}
      pretty-date: ${{ steps.date.outputs.pretty-date }}
      commit: ${{ steps.get_commit.outputs.commit }}
      channel: ${{ github.ref_name == 'main' && 'nightly' || 'nightly-branch' }}
      tag: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
      aliases: ${{ github.ref_name == 'main' && format('{0} {1}', steps.date.outputs.date, steps.get_commit.outputs.commit) || steps.get_commit.outputs.commit }}

    steps:
    - name: Get date
      id: date
      uses: alt-atomic/actions/parse-date@main

    - name: Checkout repository
      uses: actions/checkout@v4

    - id: get_commit
      name: Get current commit
      run: |
        echo "commit=$(git rev-parse HEAD)" >> $FORGEJO_OUTPUT

  build:
    name: Build ${{ matrix.arch }} images
    needs:
    - gather-build-data
    runs-on: ${{ matrix.runner }}
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus
    strategy:
      matrix:
        arch:
        - amd64
        include:
        - arch: amd64
          runner: als-huge

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ needs.gather-build-data.outputs.commit }}

    - name: Build default image
      id: build-default
      uses: alt-atomic/actions/build-and-push@79d44bd09148e22c2fb5ad195e7fed49e5d34d8c
      with:
        image-name: ${{ format('{0}/{1}/{2}', github.repository, needs.gather-build-data.outputs.channel, matrix.arch) }}
        image-tag: ${{ needs.gather-build-data.outputs.tag }}
        image-aliases: ${{ needs.gather-build-data.outputs.aliases }}
        arch: ${{ matrix.arch }}
        containerfile-path: ./container-files/main
        local-build-name: localhost/onyx

        registry-password: ${{ secrets.REGISTRY_TOKEN }}
        push-enabled: ${{ github.event_name != 'pull_request' }}
        rechunk-enabled: true
        experimental-use-chunkah: true

        pretty-name: ${{ env.PRETTY_NAME }}
        version: ${{ needs.gather-build-data.outputs.date }}
        vendor: ${{ env.VENDOR }}
        description: ${{ env.DESCRIPTION }}
        licenses: ${{ env.LICENSES }}
        url: ${{ env.URL }}
        authors: ${{ env.AUTHORS }}
        repo-date: ${{ needs.gather-build-data.outputs.pretty-date }}

        extra-labels: |
          org.altlinux.installer.has-initial-setup=true

        build-args: |
          IMAGE_TYPE=nightly
          IMAGE=${{ format('{0}/alt-atomic/core/nightly/{1}:{2}', env.REGISTRY, matrix.arch, needs.gather-build-data.outputs.date) }}
          VERSION=${{ needs.gather-build-data.outputs.date }}
          BUILD=default

        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}

    - name: Build nvidia image
      uses: alt-atomic/actions/build-and-push@79d44bd09148e22c2fb5ad195e7fed49e5d34d8c
      with:
        image-name: ${{ format('{0}-nvidia/{1}/{2}', github.repository, needs.gather-build-data.outputs.channel, matrix.arch) }}
        image-tag: ${{ needs.gather-build-data.outputs.tag }}
        image-aliases: ${{ needs.gather-build-data.outputs.aliases }}
        arch: ${{ matrix.arch }}
        containerfile-path: ./container-files/main
        local-build-name: localhost/onyx-nvidia

        registry-password: ${{ secrets.REGISTRY_TOKEN }}
        push-enabled: ${{ github.event_name != 'pull_request' }}
        rechunk-enabled: true
        experimental-use-chunkah: true

        pretty-name: ${{ env.PRETTY_NAME }} (Nvidia)
        version: ${{ needs.gather-build-data.outputs.date }}
        vendor: ${{ env.VENDOR }}
        description: ${{ env.DESCRIPTION }} (Nvidia)
        licenses: ${{ env.LICENSES }}
        url: ${{ env.URL }}
        authors: ${{ env.AUTHORS }}
        repo-date: ${{ needs.gather-build-data.outputs.pretty-date }}

        extra-labels: |
          org.altlinux.installer.has-initial-setup=true

        build-args: |
          IMAGE_TYPE=nightly
          IMAGE=${{ steps.build-default.outputs.ref }}
          VERSION=${{ needs.gather-build-data.outputs.date }}
          BUILD=nvidia

        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}

  manifest:
    name: Multiarch ${{ matrix.name }} manifest push
    needs:
    - build
    - gather-build-data
    if: github.event_name != 'pull_request'
    runs-on: als-tiny
    container:
      image: altlinux.space/alt-atomic/builder-image:sisyphus
    strategy:
      matrix:
        include:
        - name: default
          suffix: ''
        - name: nvidia
          suffix: '-nvidia'

    steps:
    - name: Create manifest
      uses: alt-atomic/actions/create-manifest@0a7fd4632a415b0f4316c37d9be29325dbe32af9
      with:
        registry: ${{ env.REGISTRY }}
        registry-username: "<token>"
        registry-password: ${{ secrets.REGISTRY_TOKEN }}
        image-name: ${{ format('{0}{1}/{2}', github.repository, matrix.suffix, needs.gather-build-data.outputs.channel) }}
        arch-tags: amd64
        image-wildcard: ${{ format('{0}/{1}{2}/{3}/@ARCH@:{4}', env.REGISTRY, github.repository, matrix.suffix, needs.gather-build-data.outputs.channel, needs.gather-build-data.outputs.tag) }}
        image-tag: ${{ needs.gather-build-data.outputs.tag }}
        image-aliases: ${{ needs.gather-build-data.outputs.aliases }}
        cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
        cosign-password: ${{ secrets.COSIGN_PASSWORD }}
