name: Build noightly image
description: Build, rechunk, lint and push nightly image

inputs:
  build:
    required: true
    description: ''
  image-name:
    required: true
    description: ''
  name-pretty:
    required: true
    description: ''
  date:
    required: true
    description: ''
  pretty-date:
    required: true
    description: ''
  commit:
    required: true
    description: ''

runs:
  using: composite
  steps:
  - name: Build sisyphus default image
    run: |
      set -x

      if [[ "${{ inputs.build }}" == "default" ]]; then
        IMAGE="${{ env.REGISTRY }}/alt-atomic/core/nightly:${{ inputs.date }}"
      else
        IMAGE="${{ env.REGISTRY }}/${{ github.repository }}/nightly:${{ inputs.commit }}"
      fi

      podman build \
        --tag ${{ env.LOCAL_BUILD_NAME }} \
        --platform linux/amd64 \
        --build-arg IMAGE=$IMAGE \
        --build-arg BUILD=${{ inputs.build }} \
        --build-arg IMAGE_TYPE=nightly \
        --file ./container-files/main \
        .

  - name: Rechunk image
    uses: alt-atomic/actions/rechunk@main
    id: rechunk
    if: (github.event_name == 'push' && github.ref_name == 'main' ) || contains(fromJSON('["workflow_dispatch", "schedule"]'), github.event_name)
    with:
      ref: ${{ env.LOCAL_BUILD_NAME }}
      prev-ref: >-
        ${{ 
          github.ref_name == 'main' &&
          format('{0}/{1}/nightly:latest', env.REGISTRY, inputs.image-name) ||
          format('{0}/{1}/nightly-branch:{2}', env.REGISTRY, inputs.image-name, github.ref_name)
        }}
      labels: |
        org.altlinux.repo.date=${{ inputs.pretty-date }}
        org.opencontainers.image.title=ALT Atomic Onyx Nightly ${{ inputs.name-pretty }}
        org.opencontainers.image.description=ALT Atomic with GNOME, nightly build ${{ inputs.name-pretty }}
        org.opencontainers.image.source=https://altlinux.space/alt-atomic/onyx
        org.opencontainers.image.licenses=GPL-3.0-or-later
        org.opencontainers.image.vendor=ALT Atomic Team

  - name: Push and sign images
    uses: alt-atomic/actions/push-and-sign@main
    if: >
      contains(fromJSON('["push", "workflow_dispatch", "schedule"]'), github.event_name)
    with:
      registry: ${{ env.REGISTRY }}
      registry-username: "<token>"
      registry-password: ${{ secrets.REGISTRY_TOKEN }}
      image-name: >-
        ${{
          github.ref_name == 'main' &&
          format('{0}/nightly', inputs.image-name) ||
          format('{0}/nightly-branch', inputs.image-name)
        }}
      image-tag: >-
        ${{ 
          github.ref_name == 'main' && 
          'latest' || 
          github.ref_name 
        }}
      image-aliases: >-
        ${{ 
          github.ref_name == 'main' && 
          inputs.date || 
          ''
        }} ${{ inputs.commit }}
      local-build-name: ${{ steps.rechunk.outputs.ref }}
      cosign-image-sign: ${{ secrets.IMAGE_SIGN }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
