image: ${{ Env.IMAGE }}

modules:
  - type: include
    body:
      targets:
        - update.yml

  - name: Set branding
    type: branding
    body:
      name: alt-atomic-${{ Env.IMAGE_NAME }}
      build-type: ${{ Env.IMAGE_TYPE }}
      release-overrides:
        VERSION: ${{ Env.VERSION }}
        VARIANT: Default
        VARIANT_ID: ${{ Env.BUILD }}

  - name: Install packages
    type: include
    body:
      targets:
        - packages.yml

  - name: Copy root
    type: copy
    body:
      source: root
      destination: /
      replace: true

  - type: include
    body:
      targets:
        - network.yml
        - systemd.yml
        - settings.yml
        - kernel.yml
        - /usr/share/apm/includes/common/cleanup.yml
