name: Build Base images

on:
  schedule:
    - cron: '0 0 * * 0'  # Каждую неделю
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          install: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          target: atomic-base
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          platforms: linux/amd64
          build-args: |
            BUILD_TYPE=default

      - name: Build and push NVIDIA base image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.nv
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest-nv
          platforms: linux/amd64
          build-args: |
            BUILD_TYPE=nvidia
            IMAGE_ID=${{ steps.build.outputs.imageid }}
  